examples : add tokenization tests for gpt-neox and refactor codes
ggerganov/ggml pull request #186
Opened 2023-05-22 14:08 UTC by jaeminSon

(An attempt to fix #170)

examples : test tokenization + support utf-8 and multi-byte encodings + refactor gpt_tokenize + refactor convert-h5-to-ggml.py

2023-05-23 17:53 UTC, klosax commented on examples/common.cpp
> +    std::string utf8conv = convert_to_utf8(text_multibytes);
I reverted this in pr #184 as it breaks other models, see comment in pr #179 . I think each model will have to handle the encoding of its tokens.

2023-05-24 08:16 UTC, ggerganov requested changes

2023-05-24 08:16 UTC, ggerganov commented on examples/common.cpp
> +#endif
Do not use `#include <filesystem>`. Use `<fstream>`

2023-05-24 08:16 UTC, ggerganov commented on examples/common.cpp
> +
```suggestion
    for (size_t i = 0; i < vec1.size(); ++i) {
        if (vec1[i] != vec2[i]) return false;
    }

```

Fix this in other places too

2023-05-24 08:18 UTC, ggerganov commented on examples/prompts/tokenize_huggingface.py
> +             "rinna/japanese-gpt-neox-3.6b": "japanese-gpt-neox",
```suggestion
             "rinna/japanese-gpt-neox-3.6b": "gpt-neox-japanese",
```

For consistency in the file names, always put the language as suffix

2023-05-24 12:03 UTC, ggerganov commented on examples/common.cpp
> +}
I think this entire function is not needed.
Instead, let's explicitly provide the path to the test file in each example

2023-05-25 19:01 UTC, ggerganov approved these changes
Great job 👍 

After resolving the merge conflicts, we can merge it

2023-05-27 08:47 UTC, merged