Make the project building with Windows
ggerganov/ggml pull request #395
Opened 2023-07-17 06:26 UTC by znsoftm

Make the project Windows compatible

2023-07-17 06:27 UTC, znsoftm commented
Being compatible with CUBLAS on Windows.

2023-07-17 15:26 UTC, Green-Sky requested changes

2023-07-19 07:38 UTC, znsoftm commented on src/CMakeLists.txt
> +    if(NOT　WIN32)
where is the "space"? 
between "NOT WIN32" ?

2023-07-23 15:14 UTC, ggerganov approved these changes

2023-07-23 15:14 UTC, ggerganov commented on src/CMakeLists.txt
> +    endif()
```suggestion
    if (NOT WIN32)
        target_link_libraries(ggml PUBLIC stdc++)
    endif()
```

2023-09-08 15:08 UTC, closed without merging