Refactor unary ops in ggml
ggerganov/ggml pull request #405
Opened 2023-07-21 18:58 UTC by Ivan-Z

Resolves #313. Removes duplicated code from unary op constructors to a shared ggml_unary. No changes to usage.

2023-07-23 15:28 UTC, ggerganov requested changes
Looks good, but a few things need fixes.

I'll push a change now to finalize this

2023-07-23 15:28 UTC, ggerganov commented on src/ggml.c
> +//gmml_compute_forward_unary
```suggestion
// ggml_compute_forward_unary
```

2023-07-23 15:28 UTC, ggerganov commented on src/ggml.c
> +    ((int *) b->data)[0] = op;
The parameter passing was just updated on `master`.
Try to utilize the new `op_params` array to pass this value

2023-07-23 15:28 UTC, ggerganov commented on src/ggml.c
> +               GGML_ASSERT(false); // TODO: not implemented
Why are `GELU` and `GELU_QUICK` not implemented?

2023-07-23 15:28 UTC, ggerganov commented on src/ggml.c
> +                switch((enum ggml_unary_op)tensor->src[0]) {
This should be `tensor->src[1]` I think

2023-07-23 15:28 UTC, ggerganov commented on src/ggml.c
> +                    switch ((enum ggml_unary_op)node->src[0]) {
Should be `node->src[1]`

2023-07-23 16:18 UTC, ggerganov approved these changes
What is missing now is to figure out a neat way to print and dump the names of the unary ops, because now it will simply print `unary` which is not very useful for debugging purposes.

@slaren Do you think this change is OK?

2023-07-23 16:23 UTC, slaren commented on src/ggml.c
> +static_assert(GGML_OP_COUNT == 59, "GGML_OP_COUNT != 68");
The string needs to be updated as well.

2023-07-23 16:34 UTC, slaren commented on src/ggml.c
> +}
A check such as `GGML_ASSERT(tensor->op == GGML_OP_UNARY)` would be good here.

2023-07-23 16:41 UTC, slaren commented on src/ggml.c
> +}
I am not sure if we really need `ggml_set_unary_op`, though.

2023-07-23 16:47 UTC, slaren commented
A function that returns the name of a unary op would be useful. Maybe also one that returns either the name of the op or the name of the unary. Something like this:
```C
if (op == GGML_OP_UNARY) {
    return ggml_unary_op_name(t);
}
return ggml_op_name(t);
```

2023-07-23 19:44 UTC, merged

2023-07-25 16:24 UTC, Ivan-Z commented
Thanks for the help @ggerganov @slaren. Do we want to make a similar change for binary ops? There are only a few right now, but might be worth making the change now if ggml intends on supporting more in the future.

2023-07-25 16:28 UTC, ggerganov commented
Let's use the unary API for a while and decide later depending on if we like the API or not